template: testify
packages:
  github.com/joaoasantana/e-product-service/internal/domain/repository:
    config:
      dir: "./mocks"
      filename: "{{.SrcPackageName}}_mock.go"
      pkgname: "test"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      CategoryRepository:
      ProductRepository:
