// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"github.com/joaoasantana/e-product-service/internal/v1/domain/core/category"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the Repository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Create(entity *category.Entity) (string, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*category.Entity) (string, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(*category.Entity) string); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*category.Entity) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - entity
func (_e *MockCategoryRepository_Expecter) Create(entity interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", entity)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(entity *category.Entity)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*category.Entity))
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(s string, err error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(entity *category.Entity) (string, error)) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) FindAll() ([]category.Entity, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []category.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]category.Entity, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []category.Entity); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCategoryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockCategoryRepository_Expecter) FindAll() *MockCategoryRepository_FindAll_Call {
	return &MockCategoryRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockCategoryRepository_FindAll_Call) Run(run func()) *MockCategoryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCategoryRepository_FindAll_Call) Return(entitys []category.Entity, err error) *MockCategoryRepository_FindAll_Call {
	_c.Call.Return(entitys, err)
	return _c
}

func (_c *MockCategoryRepository_FindAll_Call) RunAndReturn(run func() ([]category.Entity, error)) *MockCategoryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) FindByID(s string) (*category.Entity, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *category.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*category.Entity, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *category.Entity); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - s
func (_e *MockCategoryRepository_Expecter) FindByID(s interface{}) *MockCategoryRepository_FindByID_Call {
	return &MockCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", s)}
}

func (_c *MockCategoryRepository_FindByID_Call) Run(run func(s string)) *MockCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCategoryRepository_FindByID_Call) Return(entity *category.Entity, err error) *MockCategoryRepository_FindByID_Call {
	_c.Call.Return(entity, err)
	return _c
}

func (_c *MockCategoryRepository_FindByID_Call) RunAndReturn(run func(s string) (*category.Entity, error)) *MockCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) FindByName(s string) (*category.Entity, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *category.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*category.Entity, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *category.Entity); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockCategoryRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - s
func (_e *MockCategoryRepository_Expecter) FindByName(s interface{}) *MockCategoryRepository_FindByName_Call {
	return &MockCategoryRepository_FindByName_Call{Call: _e.mock.On("FindByName", s)}
}

func (_c *MockCategoryRepository_FindByName_Call) Run(run func(s string)) *MockCategoryRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCategoryRepository_FindByName_Call) Return(entity *category.Entity, err error) *MockCategoryRepository_FindByName_Call {
	_c.Call.Return(entity, err)
	return _c
}

func (_c *MockCategoryRepository_FindByName_Call) RunAndReturn(run func(s string) (*category.Entity, error)) *MockCategoryRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}
